apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: global-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awsm-secret
            key: access-key
            namespace: default
          secretAccessKeySecretRef:
            name: awsm-secret
            key: secret-access-key
            namespace: default
