apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service
  labels:
    app: subscription-service
spec:
  selector:
    matchLabels:
      app: subscription-service
  template:
    metadata:
      labels:
        app: subscription-service
    spec:
      containers:
      - name: subscription-service
        image: phihung1607/subscription-svc:1.0.4-dev
        ports:
        - containerPort: 8000
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: subscription-service
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD

      initContainers:
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', 'until nslookup postgresql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']

